# values.yaml

# Airflow configuration
executor: "SequentialExecutor"  # Use SequentialExecutor for a simple setup

# Image settings
airflow:
  image:
    repository: apache/airflow
    tag: "2.9.3"  # Specify the Airflow version
    pullPolicy: IfNotPresent

# Database configuration
postgresql:
  enabled: true  # Enable the PostgreSQL dependency
  postgresqlUsername: airflow
  postgresqlPassword: airflowpassword
  postgresqlDatabase: airflow

# Service settings
web:
  service:
    type: NodePort  # Use NodePort to expose the service externally
    port: 8085      # Specify the port for the Airflow web server
    nodePort: 30000 # Optional: Specify a custom NodePort (if desired)
